version: '3.8'

services:
  tekhliq-website:
    build: .
    expose:
      - '3000'
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tekhliq-website.rule=Host(`infra.tekhliq.com`)"
      - "traefik.http.routers.tekhliq-website.entrypoints=websecure"
      - "traefik.http.routers.tekhliq-website.tls.certresolver=letsencrypt"
      - "traefik.http.services.tekhliq-website.loadbalancer.server.port=3000"
    networks:
      - traefik

networks:
  traefik:
    external: true